apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: bombastic-api
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bombastic-api
    app.kubernetes.io/part-of: trusted-content
  name: bombastic-apig2ci
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: bombastic-api
    weight: 100
status: {}
